language: java
jdk: oraclejdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
env:
  global:
  - secure: j/XfPyQ7Aw1oSyPXdtTQIufOnwSgBVT3D6C32ui93Z9iXoQXeXCKZeONfIbaoEjKFkPUFUK29MSL/Jse+23gDyZdXZ6lOgRcTDhiYbEGdkcd2mo4MJQ6mYFlNoyOu8yzCC0QZyNZKS5rgBtsW6a4ZigtCtgP1WKR8Yjy/12X1FY=
  - secure: laCnDoXhJuPk4BNu0gnnbHlvEBX1hQPbRqkVeqOrvJwj7TlhFs+VVFm8gEUHLJUpSSqE/k2/ydaierzQmNEMqiaRg3wiCuEdcdoNMugoKXoFSZEJiDDgDQsmAI5x53FYdewAHcVVngxoYorU4K2UtZzjmPpeZBWqydd9Z/pVoAg=
